#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

print_step() {
  echo ""
  echo "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv"
  echo " $1 "
  echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
  echo ""
}

print_step "PRE COMMIT HOOKS"

print_step "forge fmt"
yarn forge:fmt
print_step "solhint"
yarn lint:fix
print_step "slither (docker)"
yarn slither:docker
