name: Foundry Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  unit:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: Forge unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Setup Soldeer dependencies
        uses: ./.github/actions/setup-soldeer
      - name: Forge unit tests
        run: forge test --match-path "test/**/*.t.sol" --no-match-path "test/**/*.{integration,invariant}.t.sol"
