name: Forge E2E

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - pashov-audit-fixes

jobs:
  e2e:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: test e2e
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Forge CI
        uses: ./.github/actions/setup-foundry-ci
        with:
          workdir: contracts
          cache-prefix: forge-out-e2e
      - name: Forge e2e tests
        run: forge test --match-path "test/e2e/**/*.e2e.t.sol"
        env:
          FOUNDRY_PROFILE: ci
