name: Forge Unit

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
      - pashovgroup-audit-fixes

jobs:
  prepare:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: prepare
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Forge CI
        uses: ./.github/actions/setup-foundry-ci
        with:
          workdir: contracts
          cache-prefix: forge-out-unit-base
      - name: Upload compiled contracts
        uses: actions/upload-artifact@v4
        with:
          name: forge-out-unit-base
          path: |
            contracts/out
            contracts/cache
          if-no-files-found: error

  unit:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: test ${{ matrix.package }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          [bridge, core, governance, safetymodule, script, staking, vault]
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Foundry CI
        uses: ./.github/actions/setup-foundry-ci
        with:
          workdir: contracts
          cache-prefix: forge-out-unit-base
          compile-contracts: "false"
      - name: Download compiled contracts
        uses: actions/download-artifact@v4
        with:
          name: forge-out-unit-base
          path: contracts
      - name: Forge unit tests
        run: forge test --match-path "test/${{ matrix.package }}/**/*.t.sol" --no-match-path "test/${{ matrix.package }}/**/*.{integration,invariant,e2e}.t.sol"
        env:
          FOUNDRY_PROFILE: ci
