name: Foundry Required Tests

on:
  pull_request:
    branches:
      - main

jobs:
  required:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: Forge required tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Setup Soldeer dependencies
        uses: ./.github/actions/setup-soldeer
      - name: Forge required tests
        run: forge test --match-path "test/**/*.integration.t.sol"
