name: Solidity Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  solhint:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.draft == false }}
    name: Solhint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Setup Soldeer dependencies
        uses: ./.github/actions/setup-soldeer
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
        working-directory: .
      - name: Install dependencies
        run: yarn install --immutable
        working-directory: .
      - name: Forge fmt
        run: yarn forge:fmt
        working-directory: .
      - name: Build solhint rules
        run: yarn solhint:build
        working-directory: .
      - name: Run solhint
        run: yarn lint
        working-directory: .
